name: Scheduled regeneration
on:
  schedule:
    # Once every hour
    - cron:  '30 * * * *'
jobs:
  generate:
    if: startsWith( github.repository, 'Homebrew/' )
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@master

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - name: Install RubyGems
      run: |
        gem install bundler -v "~>1"
        bundle install --jobs 4 --retry 3

    - name: Generate site
      run: |
        git clone --depth=1 https://github.com/Homebrew/brew
        bundle exec rake yard build

        # commit and push generated files
        git add docs

        if ! git diff --no-patch --exit-code HEAD -- docs; then
          git config --global user.name "BrewTestBot"
          git config --global user.email "homebrew-test-bot@lists.sfconservancy.org"
          git commit -m "docs: updates from Homebrew/brew" docs
          git pull --rebase origin master
          git push
        fi
